version: '3.2'
services:
    zookeeper:
        image: zookeeper
        ports:
            - "2181:2181"
        tmpfs: "/datalog"
    
    kafka1:
        image: confluentinc/cp-kafka:5.3.0
        ports:
            - "9091:9091"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./data/kafka1/data:/var/lib/kafka/data
        depends_on:
            - zookeeper
        
    kafka2:
        image: confluentinc/cp-kafka:5.3.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 2
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./data/kafka2/data:/var/lib/kafka/data
        depends_on:
            - zookeeper
        
    kafka3:
        image: confluentinc/cp-kafka:5.3.0
        ports:
            - "9093:9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 3
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./data/kafka3/data:/var/lib/kafka/data
        depends_on:
            - zookeeper

    staubdata:
        build: ./datagenerator-feinstaub/
        deploy:
            replicas: 32
        environment: 
            WAIT_HOSTS: kafka1:19091, kafka2:19092, kafka3:19093
            WAIT_HOSTS_TIMEOUT: 60
        depends_on: 
            - kafka1
            - kafka2
            - kafka3

    wetterdata:
        build: ./datagenerator-wetter/
        deploy:
            replicas: 16
        environment:
            WAIT_HOSTS: kafka1:19091, kafka2:19092, kafka3:19093
            WAIT_HOSTS_TIMEOUT: 60
        depends_on:
            - kafka1
            - kafka2
            - kafka3

    consumer:
        build: ./kafka-consumer/
        image: nailuj/iot-consumer
        environment:
            WAIT_HOSTS: kafka1:19091, kafka2:19092, kafka3:19093
            WAIT_HOSTS_TIMEOUT: 60
        depends_on: 
            - kafka1
            - kafka2
            - kafka3
    
    kafka-init:
        build: ./kafka-init/
        environment:
            WAIT_HOSTS: kafka1:19091, kafka2:19092, kafka3:19093
            WAIT_HOSTS_TIMEOUT: 60
        depends_on:
            - kafka1
            - kafka2
            - kafka3
        